export const galleryImages = [
    { src: require('./static/gallery/1.jpg') },
    { src: require('./static/gallery/2.jpg') },
    { src: require('./static/gallery/3.jpg') },
    { src: require('./static/gallery/4.jpg') },
    { src: require('./static/gallery/5.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
    // { src: require('./static/gallery/.jpg') },
]
